/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/carrier/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Carrier */
        post: operations["verify_carrier_api_v1_carrier_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loads/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Loads */
        post: operations["search_loads_api_v1_loads_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/negotiate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Negotiate */
        post: operations["negotiate_api_v1_negotiate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calls/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Call */
        post: operations["log_call_api_v1_calls_log_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Calls */
        get: operations["list_calls_api_v1_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_api_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CallListItem */
        CallListItem: {
            /** Id */
            id: string;
            /** Call Id */
            call_id: string;
            /** Carrier Mc */
            carrier_mc?: string | null;
            /** Carrier Name */
            carrier_name?: string | null;
            /** Carrier Company */
            carrier_company?: string | null;
            /** Load Id Discussed */
            load_id_discussed?: string | null;
            /** Loadboard Rate */
            loadboard_rate?: string | null;
            /** Initial Carrier Ask */
            initial_carrier_ask?: string | null;
            /** Final Agreed Rate */
            final_agreed_rate?: string | null;
            /** Negotiation Rounds */
            negotiation_rounds: number;
            outcome: components["schemas"]["CallOutcome"];
            sentiment: components["schemas"]["CarrierSentiment"];
            equipment_type_requested?: components["schemas"]["EquipmentType"] | null;
            /** Origin Requested */
            origin_requested?: string | null;
            /** Destination Requested */
            destination_requested?: string | null;
            /** Call Duration Seconds */
            call_duration_seconds?: number | null;
            /** Transcript Summary */
            transcript_summary?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CallListResponse */
        CallListResponse: {
            /** Items */
            items: components["schemas"]["CallListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** CallLogRequest */
        CallLogRequest: {
            /** Call Id */
            call_id: string;
            /** Carrier Mc */
            carrier_mc?: string | null;
            /** Carrier Name */
            carrier_name?: string | null;
            /** Carrier Company */
            carrier_company?: string | null;
            /** Load Id Discussed */
            load_id_discussed?: string | null;
            /** Loadboard Rate */
            loadboard_rate?: number | string | null;
            /** Initial Carrier Ask */
            initial_carrier_ask?: number | string | null;
            /** Final Agreed Rate */
            final_agreed_rate?: number | string | null;
            /**
             * Negotiation Rounds
             * @default 0
             */
            negotiation_rounds: number;
            /**
             * Transferred
             * @default false
             */
            transferred: boolean;
            /** Vetting Passed */
            vetting_passed?: boolean | null;
            /**
             * Loads Searched
             * @default false
             */
            loads_searched: boolean;
            /**
             * Matches Returned
             * @default 0
             */
            matches_returned: number;
            equipment_type_requested?: components["schemas"]["EquipmentType"] | null;
            /** Origin Requested */
            origin_requested?: string | null;
            /** Destination Requested */
            destination_requested?: string | null;
            /** Call Duration Seconds */
            call_duration_seconds?: number | null;
            /** Transcript Summary */
            transcript_summary?: string | null;
            sentiment?: components["schemas"]["CarrierSentiment"] | null;
        };
        /** CallLogResponse */
        CallLogResponse: {
            /** Call Id */
            call_id: string;
            outcome: components["schemas"]["CallOutcome"];
            sentiment: components["schemas"]["CarrierSentiment"];
        };
        /**
         * CallOutcome
         * @enum {string}
         */
        CallOutcome: "booked" | "no_matching_loads" | "carrier_declined_rate" | "carrier_failed_vetting" | "negotiation_stalled" | "carrier_hung_up" | "transferred_to_rep";
        /**
         * CarrierSentiment
         * @enum {string}
         */
        CarrierSentiment: "positive" | "neutral" | "skeptical" | "frustrated" | "hostile";
        /** CarrierVerifyRequest */
        CarrierVerifyRequest: {
            /**
             * Mc
             * @description MC docket number digits only.
             */
            mc: string;
        };
        /** CarrierVerifyResponse */
        CarrierVerifyResponse: {
            /** Mc Number */
            mc_number: string;
            /** Legal Name */
            legal_name?: string | null;
            /** Dba Name */
            dba_name?: string | null;
            /** Operating Status */
            operating_status?: string | null;
            /** Authority Type */
            authority_type?: string | null;
            /** Allowed To Operate */
            allowed_to_operate?: boolean | null;
            /** Safety Rating */
            safety_rating?: string | null;
            /** Insurance Bipd On File */
            insurance_bipd_on_file?: string | null;
            /** Insurance Cargo On File */
            insurance_cargo_on_file?: string | null;
            /** Is Eligible */
            is_eligible?: boolean | null;
            /** Rejection Reason */
            rejection_reason?: string | null;
            /** Verified At */
            verified_at?: string | null;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
        };
        /** EquipmentDemand */
        EquipmentDemand: {
            equipment_type: components["schemas"]["EquipmentType"];
            /** Count */
            count: number;
        };
        /**
         * EquipmentType
         * @enum {string}
         */
        EquipmentType: "dry_van" | "reefer" | "flatbed" | "step_deck" | "power_only";
        /** FunnelSection */
        FunnelSection: {
            /** Stages */
            stages: components["schemas"]["FunnelStage"][];
        };
        /** FunnelStage */
        FunnelStage: {
            /** Name */
            name: string;
            /** Count */
            count: number;
            /** Drop Off Pct */
            drop_off_pct: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KPIBar */
        KPIBar: {
            /** Calls Today */
            calls_today: number;
            /** Booked Rate Pct */
            booked_rate_pct: number;
            /** Avg Margin Saved Usd */
            avg_margin_saved_usd: string;
            /** Avg Negotiation Rounds */
            avg_negotiation_rounds: number;
        };
        /** LaneVolume */
        LaneVolume: {
            /** Origin */
            origin: string;
            /** Destination */
            destination: string;
            /** Count */
            count: number;
        };
        /** LoadMatch */
        LoadMatch: {
            /** Load Id */
            load_id: string;
            /** Origin */
            origin: string;
            /** Destination */
            destination: string;
            /**
             * Pickup Datetime
             * Format: date-time
             */
            pickup_datetime: string;
            /**
             * Delivery Datetime
             * Format: date-time
             */
            delivery_datetime: string;
            equipment_type: components["schemas"]["EquipmentType"];
            /** Loadboard Rate */
            loadboard_rate: string;
            /** Notes */
            notes?: string | null;
            /** Weight */
            weight: number;
            /** Commodity Type */
            commodity_type: string;
            /** Num Of Pieces */
            num_of_pieces: number;
            /** Miles */
            miles: number;
            /** Dimensions */
            dimensions: string;
            /** Score */
            score: number;
            /** Rate Per Mile */
            rate_per_mile: string;
        };
        /** LoadMatchingSection */
        LoadMatchingSection: {
            /** Top Lanes */
            top_lanes: components["schemas"]["LaneVolume"][];
            /** Equipment Demand */
            equipment_demand: components["schemas"]["EquipmentDemand"][];
        };
        /** LoadSearchRequest */
        LoadSearchRequest: {
            /**
             * Origin
             * @description Free-form origin string from the carrier.
             */
            origin?: string | null;
            /**
             * Destination
             * @description Free-form destination string.
             */
            destination?: string | null;
            equipment_type?: components["schemas"]["EquipmentType"] | null;
            /**
             * Pickup Date
             * @description Target pickup date — matched within +/- 2 days.
             */
            pickup_date?: string | null;
            /**
             * Max Results
             * @default 3
             */
            max_results: number;
        };
        /** LoadSearchResponse */
        LoadSearchResponse: {
            /** Matches */
            matches: components["schemas"]["LoadMatch"][];
            /** Total Found */
            total_found: number;
            /**
             * Partial
             * @default false
             */
            partial: boolean;
            /** Message */
            message?: string | null;
        };
        /** MetricsResponse */
        MetricsResponse: {
            /**
             * Period
             * @enum {string}
             */
            period: "today" | "7d" | "30d" | "all";
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            kpi: components["schemas"]["KPIBar"];
            funnel: components["schemas"]["FunnelSection"];
            revenue: components["schemas"]["RevenueSection"];
            negotiation: components["schemas"]["NegotiationSection"];
            vetting: components["schemas"]["VettingSection"];
            sentiment: components["schemas"]["SentimentSection"];
            load_matching: components["schemas"]["LoadMatchingSection"];
            timeseries: components["schemas"]["TimeseriesSection"];
            /** Recent Calls */
            recent_calls: components["schemas"]["RecentCallItem"][];
        };
        /** NegotiateRequest */
        NegotiateRequest: {
            state: components["schemas"]["NegotiationState-Input"];
            /** Carrier Offer */
            carrier_offer: number | string;
            carrier_sentiment?: components["schemas"]["CarrierSentiment"] | null;
        };
        /** NegotiateResponse */
        NegotiateResponse: {
            state: components["schemas"]["NegotiationState-Output"];
            /** Suggested Response */
            suggested_response: string;
            /** Counter Offer */
            counter_offer?: string | null;
        };
        /** NegotiationRoundBucket */
        NegotiationRoundBucket: {
            /** Round */
            round: number;
            /** Agreed */
            agreed: number;
            /** Walked */
            walked: number;
            /** Avg Discount Pct */
            avg_discount_pct: number;
        };
        /** NegotiationSection */
        NegotiationSection: {
            /** Buckets */
            buckets: components["schemas"]["NegotiationRoundBucket"][];
        };
        /** NegotiationState */
        "NegotiationState-Input": {
            /** Load Id */
            load_id: string;
            /** Loadboard Rate */
            loadboard_rate: number | string;
            /**
             * Round
             * @default 0
             */
            round: number;
            /** Agent Last Offer */
            agent_last_offer?: number | string | null;
            /** Carrier Last Offer */
            carrier_last_offer?: number | string | null;
            /** Final Rate */
            final_rate?: number | string | null;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "agreed" | "walked_away";
        };
        /** NegotiationState */
        "NegotiationState-Output": {
            /** Load Id */
            load_id: string;
            /** Loadboard Rate */
            loadboard_rate: string;
            /**
             * Round
             * @default 0
             */
            round: number;
            /** Agent Last Offer */
            agent_last_offer?: string | null;
            /** Carrier Last Offer */
            carrier_last_offer?: string | null;
            /** Final Rate */
            final_rate?: string | null;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "agreed" | "walked_away";
        };
        /** RecentCallItem */
        RecentCallItem: {
            /** Call Id */
            call_id: string;
            /** Carrier Mc */
            carrier_mc: string | null;
            /** Carrier Name */
            carrier_name: string | null;
            /** Carrier Company */
            carrier_company: string | null;
            /** Load Id Discussed */
            load_id_discussed: string | null;
            /** Loadboard Rate */
            loadboard_rate: string | null;
            /** Final Agreed Rate */
            final_agreed_rate: string | null;
            /** Negotiation Rounds */
            negotiation_rounds: number;
            outcome: components["schemas"]["CallOutcome"];
            sentiment: components["schemas"]["CarrierSentiment"];
            /** Origin Requested */
            origin_requested: string | null;
            /** Destination Requested */
            destination_requested: string | null;
            equipment_type_requested: components["schemas"]["EquipmentType"] | null;
            /** Transcript Summary */
            transcript_summary: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RevenueSection */
        RevenueSection: {
            /** Avg Loadboard Rate */
            avg_loadboard_rate: string;
            /** Avg Booked Rate */
            avg_booked_rate: string;
            /** Avg Margin Preserved Pct */
            avg_margin_preserved_pct: number;
        };
        /** SentimentDistribution */
        SentimentDistribution: {
            sentiment: components["schemas"]["CarrierSentiment"];
            /** Count */
            count: number;
        };
        /** SentimentOutcomeCell */
        SentimentOutcomeCell: {
            sentiment: components["schemas"]["CarrierSentiment"];
            outcome: components["schemas"]["CallOutcome"];
            /** Count */
            count: number;
        };
        /** SentimentSection */
        SentimentSection: {
            /** Distribution */
            distribution: components["schemas"]["SentimentDistribution"][];
            /** Heatmap */
            heatmap: components["schemas"]["SentimentOutcomeCell"][];
        };
        /** TimeseriesPoint */
        TimeseriesPoint: {
            /**
             * Bucket Start
             * Format: date-time
             */
            bucket_start: string;
            /** Calls */
            calls: number;
            /** Booked */
            booked: number;
        };
        /** TimeseriesSection */
        TimeseriesSection: {
            /** Points */
            points: components["schemas"]["TimeseriesPoint"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VettingSection */
        VettingSection: {
            /** Pass Count */
            pass_count: number;
            /** Fail Count */
            fail_count: number;
            /** Top Failure Reasons */
            top_failure_reasons: {
                [key: string]: number | string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    verify_carrier_api_v1_carrier_verify_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarrierVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarrierVerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_loads_api_v1_loads_search_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    negotiate_api_v1_negotiate_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NegotiateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NegotiateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_call_api_v1_calls_log_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CallLogRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_calls_api_v1_calls_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                outcome?: components["schemas"]["CallOutcome"] | null;
                sentiment?: components["schemas"]["CarrierSentiment"] | null;
                page?: number;
                page_size?: number;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_api_v1_metrics_get: {
        parameters: {
            query?: {
                period?: "today" | "7d" | "30d" | "all";
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
